image: node:7.10-alpine
#services:
#  - postgres

before_script:
  - npm install

#after_script:
#  - rm secrets

stages:
  - build
  - test
#  - deploy

job1:
  stage: build
  script:
    - npm run build
#  only:
#    - master
  tags:
    - docker

job2:
  stage: test
  script:
    - npm run test
#  only:
#    - master
  tags:
    - docker
